### ISSUE TITLE
Cannot listen on gateway metadata changes

### ISSUE THREAD

**Issue by jeroenhansen** [ibm-watson-iot/iot-java#145] opened 2018-12-04 21:50 UTC
I am trying to run a gateway that takes its metadata from Watson IoT. Whenever the metadata changes in Watson IoT the propertyChangeListener should fire.
When doing this for a ManagedDevice, this works fine, however for  ManagedGateway I either get an NPE or the Metadata in Watson IoT is wiped out or overwritten when the gateway starts.

The sample code below may be used to try out the concept:
- Define a Gateway in your Watson IoT instance
- Update the 4 constants to match your settings
- Run this code as a Java application
- Update the metadata in Watson IoT for the Gateway
- And watch the propertyChangedListener fire
- Restart this Gateway and watch what happens to the metadata you just entered. It is gone.

For ManagedDevices it is possible to use option 3. But for ManagedGateways this does not work.

I think this is a bug at the following line:

https://github.com/ibm-watson-iot/iot-java/blob/f2a732a87dad7f17ee0fd654f5b95e9a11ef669c/src/main/java/com/ibm/iotf/devicemgmt/gateway/ManagedGateway.java#L667

The jsonMetaData.isJsonNull() is always false because jsonMetaData is a JsonObject which cannnot equal a JsonNull.

```
package iot.wiot.devicemanagement;

import com.google.gson.JsonObject;
import com.ibm.iotf.devicemgmt.DeviceData;
import com.ibm.iotf.devicemgmt.DeviceMetadata;
import com.ibm.iotf.devicemgmt.gateway.ManagedGateway;
import java.util.Properties;
import java.util.Random;

public class IotfManagedGatewayIssue {

  private static final String ORGID = "YOUR ORGID";
  private static final String GATEWAY_TYPE = "YOUR GATEWAY TYPE";
  private static final String GATEWAY_ID = "YOUR GATEWAY ID";
  private static final String TOKEN = "YOUR TOKEN";

  public static void main(String[] args) throws Exception {
    // Create the properties to log in
    final Properties properties = new Properties();
    properties.setProperty("org", ORGID);
    properties.setProperty("type", GATEWAY_TYPE);
    properties.setProperty("id", GATEWAY_ID);
    properties.setProperty("auth-method", "token");
    properties.setProperty("auth-token", TOKEN);

    // Create a DeviceData object - option 1 => NPE at line 78
    final DeviceData deviceData1 = new DeviceData.Builder()
        .typeId(GATEWAY_TYPE).deviceId(GATEWAY_ID).build();
    
    // Create a DeviceData object - option 2 => NPE at line 78
    final DeviceData deviceData2 = new DeviceData.Builder()
        .typeId(GATEWAY_TYPE).deviceId(GATEWAY_ID)
        .metadata(null).build();

    // Create a DeviceData object - option 3 
    // => NPE at com.ibm.iotf.devicemgmt.gateway.ManagedGateway.sendDeviceManageRequest(ManagedGateway.java:666)
    final DeviceMetadata metadata3 = new DeviceMetadata(null);
    final DeviceData deviceData3 = new DeviceData.Builder()
        .typeId(GATEWAY_TYPE).deviceId(GATEWAY_ID)
        .metadata(metadata3).build();

    // Create a DeviceData object - option 4 
    // => this clears out the metadata in Watson IoT on the Gateway
    final DeviceMetadata metadata4 = new DeviceMetadata(new JsonObject());
    final DeviceData deviceData4 = new DeviceData.Builder()
        .typeId(GATEWAY_TYPE).deviceId(GATEWAY_ID)
        .metadata(metadata4).build();

    // Create a DeviceData object - option 5 => Does not compile
    //final DeviceMetadata metadata5 = new DeviceMetadata(JsonNull.INSTANCE);
    //final DeviceData deviceData5 = new DeviceData.Builder()
    //    .typeId(GATEWAY_TYPE).deviceId(GATEWAY_ID)
    //    .metadata(metadata5).build();
    
    
    // Create the managed gateway using properties and deviceData 
    final ManagedGateway managedGateway = new ManagedGateway(properties, deviceData1);

    managedGateway.connect();

    // Create a separate thread for the next actions
    new Thread(() -> {
      try {
        // publish a simple random message to prove that the MQTT connection works
        publishAliveMessage(managedGateway);

        // send manage request
        final boolean result = managedGateway.sendGatewayManageRequest(0, false, false);
        System.out.println("sendManageRequest: " + result);

        // add a property change listeners to the deviceInfo
        managedGateway.getGatewayDeviceData().getDeviceInfo().addPropertyChangeListener(evt -> {
          System.out.println("PropertyChangeEvent:" + evt.getPropertyName());
          System.out.println("  toString:" + evt.toString());
        });

        // add a property change listener to metadata
        managedGateway.getGatewayDeviceData().getMetadata().addPropertyChangeListener(evt -> {
          System.out.println("PropertyChangeEvent:" + evt.getPropertyName());
          System.out.println("  toString:" + evt.toString());
        });

      } catch (Exception e) {
        e.printStackTrace();
      }
    }).start();

    // Now just let all the threads run
    
    // - Manually update the DeviceInfo and Metadata of the Gateway in Watson IoT
    // - Look for the PropertyChangeEvents on sysout
  }

  private static void publishAliveMessage(ManagedGateway managedGateway) {
    final JsonObject event = new JsonObject();

    final Random r = new Random();
    event.addProperty("cpu", r.nextInt(100));
    event.addProperty("mem", r.nextInt(100));
    event.addProperty("lat", 52.151672 + r.nextGaussian() / 100);
    event.addProperty("lon", 4.665778 + r.nextGaussian() / 100);

    System.out.println("Publishing " + event.toString());

    managedGateway.publishGatewayEvent("status", event, 0);
    System.out.println("Sucssessfully published message");
  }
}
```

**Comment by miketran78727** [comment] 2018-12-04 21:56
I'll investigate.  Thanks for submitting the issue.

**Comment by miketran78727** [comment] 2019-01-10 22:07
@jeroenhansen 

If you instantiate the DeviceData object with null DeviceMetadata, NPE will be thrown on the 
```
managedGateway.getGatewayDeviceData().getMetadata().addPropertyChangeListener( ... )
```

What will happen if you create an empty DeviceMetadata and pass it to the DeviceData builder? i.e.

```
final DeviceMetadata emptyMetadata = new DeviceMetadata(new JsonObject());
final DeviceData deviceData = new DeviceData.Builder()
        .typeId(GATEWAY_TYPE).deviceId(GATEWAY_ID)
        .metadata(emptyMetadata ).build();
```

**Comment by miketran78727** [comment] 2019-01-11 18:41
If metadata is not specified, create an empty object. Merged https://github.com/ibm-watson-iot/iot-java/pull/146

**Comment by jeroenhansen** [comment] 2019-01-11 19:46
The suggested solution clears out the Metadata of the Gateway in Watson IoT, which is not what is desired. A solution is needed in which Watson IoT is the master of the metadata and in which the gateway listens to changes.
For Devices this is possible using version 0.2.6 of the library but for Gateways this does not work.

**Comment by miketran78727** [comment] 2019-01-16 15:22
@jeroenhansen 
I am trying to understand the problem.  I have updated the tests to check for metadata changes.  

https://github.com/ibm-watson-iot/iot-java/blob/master/src/test/java/com/ibm/iotf/client/gateway/GatewayManagementTest2.java#L127

I don't see the issue where the metadata was cleared out in Watson IoT Platform or the Gateway Client:

```
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: Running test #1
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.AbstractClient createClient
INFO: pool-1-thread-1: Org ID    = [secure]
         Client ID    = g:[secure]:GwMgmtType2:GwMgmtDev2_1
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: Created managed gateway client
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.AbstractClient connect
INFO: pool-1-thread-1: Initiating Token based authentication
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.AbstractClient connect
INFO: pool-1-thread-1: Connecting client g:[secure]:GwMgmtType2:GwMgmtDev2_1 to ssl://[secure].messaging.internetofthings.ibmcloud.com:8883 (attempt #1)...
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.gateway.GatewayClient connectComplete
INFO: MQTT Call: g:[secure]:GwMgmtType2:GwMgmtDev2_1: g:[secure]:GwMgmtType2:GwMgmtDev2_1 reconnected (false) URI: ssl://[secure].messaging.internetofthings.ibmcloud.com:8883
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.AbstractClient connect
INFO: pool-1-thread-1: g:[secure]:GwMgmtType2:GwMgmtDev2_1 successfully connected to the IBM Watson IoT Platform
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: connected (true)
Jan 16, 2019 3:15:42 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: Testing sendGatewayManageRequest(0, false, false)
Jan 16, 2019 3:15:43 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: Current Metadata : {}
Jan 16, 2019 3:15:43 PM com.ibm.iotf.test.common.TestPropertyChangeListener propertyChange
INFO: pool-15-thread-2: Changed Property : metadata
Jan 16, 2019 3:15:43 PM com.ibm.iotf.test.common.TestPropertyChangeListener propertyChange
INFO: pool-15-thread-2: Old value : null New value : {"test":1}
Jan 16, 2019 3:15:43 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: New Value : {"test":1}
Jan 16, 2019 3:15:43 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: Metadata from Watson IoT Platform API : {"test":1}
Jan 16, 2019 3:15:43 PM com.ibm.iotf.client.gateway.GatewayManagementTest2 test01ManageRequest
INFO: pool-1-thread-1: Metadata from Gateway Client : {"test":1}
Jan 16, 2019 3:15:43 PM com.ibm.iotf.client.AbstractClient disconnect
INFO: pool-1-thread-1: g:[secure]:GwMgmtType2:GwMgmtDev2_1 is disconnecting from the IBM Watson IoT Platform ...
Jan 16, 2019 3:15:43 PM com.ibm.iotf.client.AbstractClient disconnect
INFO: pool-1-thread-1: g:[secure]:GwMgmtType2:GwMgmtDev2_1 successfully disconnected from the IBM Watson IoT Platform
```

**Comment by miketran78727** [comment] 2019-01-16 15:28
@jeroenhansen 
Are you seeing the issue in UI ?

**Comment by jeroenhansen** [comment] 2019-01-16 16:15
Yes, when I first type something into the Metadata field in the UI and save that, then start a gateway with an empty JsonObject as metadata, the result is that the contents of the Metadata in the UI have been wiped. When I then type something new and save, the propertylistener fires as expected with that new json.

Op 16 jan. 2019 16:28:58, schreef notifications@github.com:

**Comment by miketran78727** [comment] 2019-01-16 16:21
@jeroenhansen Thanks for clarification.  I will pass this issue to the UI team.

**Comment by miketran78727** [comment] 2019-01-16 16:35
Let me try with one more new test to see if I can reproduce this problem in Java Client Library.

**Comment by miketran78727** [comment] 2019-01-16 23:00
@jeroenhansen I have fixed the issue so that if you specify an empty Metadata object {}, the existing metadata will not be wiped out.  This way, you can have a listener on metadata changes.

Note that by design, when the gateway client sends manage request, it will update metadata if it is specified when DeviceData object is instantiated. So, to reserve the existing device metadata, you will need to get from Watson IoT Platform and provide that metadata to create the DeviceData object.

See my test code : https://github.com/ibm-watson-iot/iot-java/blob/master/src/test/java/com/ibm/iotf/client/gateway/GatewayManagementTest2.java#L155

**Closed as completed by miketran78727** 2019-01-16 23:00 UTC
Labels: bug, fix implemented

**Comment by miketran78727** [comment] 2019-01-16 23:02
This fix will be available in the next release.  If you want to try it, you can clone the master branch and build it locally.
