### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by ValkA** [ibm-watson-iot/iot-java#113] opened 2017-11-29 13:20 UTC
Hi, 
I've added the library into android studio project with `compile group: 'com.ibm.messaging', name: 'watson-iot', version: '0.2.6'` in build.gradle.
The project compiles but I get the following exception when calling: `res = apiClient.registerDevice("Android", dev);`

ava.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/nio/charset/Charset;)V in class Lorg/apache/http/entity/StringEntity; or its super classes (declaration of 'org.apache.http.entity.StringEntity' appears in /system/framework/org.apache.http.legacy.boot.jar)
                                                                            at com.ibm.iotf.client.api.APIClient.connect(APIClient.java:264)
                                                                            at com.ibm.iotf.client.api.APIClient.registerDevice(APIClient.java:1620)
                                                                            at com.valka.simusafe_android.MainActivity.onCreate(MainActivity.java:57)
                                                                            at android.app.Activity.performCreate(Activity.java:6975)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                            at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

After some investigation seems like this happens because using the generic httpclient library instead of httpclient-android.

Is android support planned to be added to the library ?
Or is there a workaround to make it run on android ?

Thanks,
Valentin.

**Comment by amitmangalvedkar** [comment] 2018-01-29 09:01
We have passed this request of providing an Android library to the architecture team and will get back to you, once we have the final response.

**Comment by amitmangalvedkar** [comment] 2018-02-15 07:30
This is duplicate of [106](https://github.com/ibm-watson-iot/iot-java/issues/106) and so closing this one.

**Closed as completed by amitmangalvedkar** 2018-02-15 07:30 UTC
