### ISSUE TITLE
Device Status subscription MQTT disconnects continuously

### ISSUE THREAD

**Issue by simone201** [ibm-watson-iot/iot-java#77] opened 2016-12-12 15:23 UTC
In a Java server application I'm using the IoT library to listen to Device messages, and everything works fine.
Now I'm trying to listen to Device status messages (connection, disconnection) just using the sample code found in the samples, without any luck.
Once i enable the subscription, with or without deviceId and device name, the connection continues to connect and disconnect to the MQTT endpoint with an error like this:

`INFORMAZIONI: MQTT Rec: a:fdo3mr:26a0e6cc-e092-4a11-a741-2e4068aa9231: Successfully connected to the IBM Watson IoT Platform
dic 12, 2016 3:23:52 PM com.ibm.iotf.client.app.ApplicationClient connectionLost
INFORMAZIONI: MQTT Rec: a:fdo3mr:26a0e6cc-e092-4a11-a741-2e4068aa9231: Resubscribing....
dic 12, 2016 3:23:52 PM com.ibm.iotf.client.app.ApplicationClient connectionLost
INFORMAZIONI: MQTT Rec: a:fdo3mr:26a0e6cc-e092-4a11-a741-2e4068aa9231: iot-2/type/DellGateway/id/+/mon = 0
dic 12, 2016 3:23:52 PM com.ibm.iotf.client.app.ApplicationClient connectionLost
GRAVE: MQTT Rec: a:fdo3mr:26a0e6cc-e092-4a11-a741-2e4068aa9231: Connessione persa
Connessione persa (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	... 1 more`

Any ideas or any potential bug in the library that may cause this kind of issues?

**Comment by miketran78727** [comment] 2016-12-14 14:31
@simone201 In your application, how many instances of ApplicationClient do you have? Could you please post the relevant code that you use to listen to Device status messages?

**Comment by simone201** [comment] 2016-12-14 14:43
@miketran78727 Just one simple ApplicationClient object stored in a Servlet (which works fine to just get and send messages).
Here's linked the subscribe method: http://pastebin.com/U4v6UCPM

the Device Status Callback is just a simple class that implements the StatusCallback interface as showed in the examples. That method is called during init of the main servlet in the application.

**Comment by miketran78727** [comment] 2016-12-15 17:15
@simone201 I could not reproduce the problem in a web application or a simple Java application.

**Comment by sathipal** [comment] 2017-02-24 05:30
@simone201 are you still observing the issue?

**Comment by sathipal** [comment] 2017-05-03 04:11
@simone201 are you still observing the issue?

**Comment by simone201** [comment] 2017-05-03 07:47
@sathipal yeah same issue with any new release

**Comment by amprasanna** [comment] 2017-06-05 09:34
@simone201 - Can you please share your test sample or the sample script that shall help us reproduce the issue and debug the same.

**Comment by amitmangalvedkar** [comment] 2017-06-21 07:37
@simone201 - Can you please share your test sample as @amprasanna suggested?

**Comment by amprasanna** [comment] 2017-06-23 06:33
@simone201 - Assuming you are no longer running into this issue, I'm going ahead and closing this Issue at this point of time. Should you have any reservations or a test sample to help recreate the issue, please plan to either re-open the Issue or open a new one, altogether.

**Closed as completed by amprasanna** 2017-06-23 06:33 UTC
