### ISSUE TITLE
System.exit in connect method

### ISSUE THREAD

**Issue by oriolpinol** [ibm-watson-iot/iot-java#15] opened 2016-03-09 11:05 UTC
Hi! First of all thanks for your great work, this sdk helps a lot with integration with IBM Watson IoT Platform. 

I noticed that recently when there is an MqttException or MqttSecurityException in the connect method in the AbstractClient System.exit(-1) is called, causing any application using the library to immediately terminate because of a failed connection attempt (maybe simply mistype a authenticationToken). This makes the library almost unusable for many applications. Is there any plan to modify this behaviour in the near future such as throwing the exceptions and let the consumer of the library decide how to react to failures?

Thank you very much and keep up the good work!

**Comment by sathipal** [comment] 2016-03-09 11:38
@oriolpinol, Thank you for reporting the issue. I think throwing the exception sounds good. I'll discuss with the team and take action accordingly.

**Comment by sathipal** [comment] 2016-03-23 05:07
Thank you for reporting the issue !

The issue is fixed in the github, now the library will throw an exception when the connection attempt is failed in the following scenarios,
1. When there is a MqttSecurityException - One or more credentials are wrong
2. When there is a UnKnownHostException - Host doesn't exist. For example, a wrong organization name is used to connect.

But it it receives host not reachable exception, it retries.

**Closed as completed by sathipal** 2016-03-23 05:07 UTC
