### ISSUE TITLE
Problem with DeviceClient certificate based authentication.

### ISSUE THREAD

**Issue by martinlobe** [ibm-watson-iot/iot-java#115] opened 2018-01-03 06:54 UTC
Hi,

it seams to me there is a small problem with certificate based authentication.
If you want to use certificate based authentication with the DeviceClient you have to specify a server certificate. With the default certificate in WIoT that should not be necessary and instead the truststore should be searched for a valid certificate in the trust chain. That is currently not possible.
(see https://github.com/ibm-watson-iot/iot-java/blob/e969d1a8206a6bc74958e7486105b70f1db3b25b/src/main/java/com/ibm/iotf/client/AbstractClient.java#L505 )
I had to explicitly define the DigiCert signer cert as the Server Certificate to be able to connect. Although the DigiCert root CA is in the trust store and loaded during initialization. In case one used a custom server certificate for WIoT the same should apply -> add the cert to the trust store (if specified) and go on.

If i missed something to make it work, please correct me. However, the sample at https://developer.ibm.com/recipes/tutorials/connect-raspberry-pi-to-ibm-watson-iot-platform-using-selfsigned-server-certificate/
is not working when "translated" to java.

Another thing is, why is the client trying to reconnect when there is no valid certificate to verify the server certificate? That's a dead end and should break the cycle immediately with a propper error message.

Sample code used:
Properties properties = new Properties();
properties.put("Organization-ID", "yourOrg");
properties.put("Authentication-Method", "token");
properties.put("Authentication-Token", "yourToken");
properties.put("Device-ID", "yourDeviceId");
properties.put("Device-Type", "yourDeviceType");
properties.put("Use-Secure-Certificate", "true");
properties.put("Server-Certificate", "/path/to/rootCA.pem"); #should not be necessary with default cert
properties.put("Client-Certificate", "/path/to/client.pem");
properties.put("Client-Key", "/path/to/client.key");

com.ibm.iotf.client.device.DeviceClient deviceClient = new DeviceClient(properties);
deviceClient.connect();

**Comment by sathipal** [comment] 2018-02-15 10:48
Hi,

Thanks for reporting the issue, I hope the issue here maybe because you are not setting the password for the client certificate, (The iot-java library i think doesn't handle well when the certificates are created without the password). Can you try generating the certificate with a password and pass the same via "Certificate-Password" property as shown below?

Properties properties = new Properties();
properties.put("Organization-ID", "yourOrg");
properties.put("Authentication-Method", "token");
properties.put("Authentication-Token", "yourToken");
properties.put("Device-ID", "yourDeviceId");
properties.put("Device-Type", "yourDeviceType");
properties.put("Use-Secure-Certificate", "true");
properties.put("Server-Certificate", "/path/to/rootCA.pem"); #should not be necessary with default cert
properties.put("Client-Certificate", "/path/to/client.pem");
properties.put("Client-Key", "/path/to/client.key");

**properties.put("Certificate-Password", "your certificate password");**

we will work on the other issues that you raised here.

**Comment by sathipal** [comment] 2018-02-15 12:45
The issue is addressed in this pull request - https://github.com/ibm-watson-iot/iot-java/pull/121

**Comment by sathipal** [comment] 2018-02-16 06:13
Closing as the changes are delivered in master. Please reopen incase if there are any issues still.

**Closed as completed by sathipal** 2018-02-16 06:13 UTC
